#!/bin/bash
# script to generate other scripts
rm script_temp
for n in "128" "256" "512" "1024" "2048"
do
	./makemat $n 0
	for r in 1 2 8 16 64
	do
		for p in 1 2 4 8 16
		do
			for mode in 0 1
			do
				echo "#!/bin/bash" >>script_temp
				echo "#PBS -l walltime=5:00" >>script_temp
				if [ $p -eq 16 ] 
				then
					echo "#PBS -l nodes=4:ppn=4" >>script_temp
				elif [ $p -eq 8 ] 
				then
					echo "#PBS -l nodes=2:ppn=4" >>script_temp
				elif [ $p -eq 4 ] 
				then
					echo "#PBS -l nodes=1:ppn=4" >>script_temp
				elif [ $p -eq 2 ] 
				then
					echo "#PBS -l nodes=1:ppn=2" >>script_temp
				else
					echo "#PBS -l nodes=$p:ppn=1" >>script_temp
				fi
				
				#echo "#PBS -m be" >>script_temp
				echo "#PBS -o ge_parallel.output" >>script_temp
				echo "#PBS -e ge_parallel.error.output" >>script_temp
                echo "cd ~afebre2/gaussianator" >>script_temp
				echo "/usr/common/mpich2/bin/mpiexec ./parallel_GE_alessandro $mode $r $n matrix_${n}_0.txt 1 test > output.txt 2>&1" >>script_temp
				#echo "***********************************************" >> script_temp
				qsub -V -q student_short script_temp  
				rm script_temp								
				sleep 10
			done		
		done
	done	 
done	